name: bp_env
channels:
  - conda-forge
dependencies:
  - cmake=3.26.4
  - python=3.8
  - av=10.0.0
  - dlib=19.24.2
  - face_recognition=1.3.0
  - imutils=0.5.4
  - numpy=1.24.3
  - scipy=1.10.1
  - pip
  - pip:
      - opencv_python=4.7.0.72
      - opencv_python_headless=4.7.0.72
